server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #本地测试使用
    url: jdbc:mysql://127.0.0.1:3306/cloudTest?characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

eureka:
  client:
    #表示是否将自己注册在Eurekaserver 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为ture才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001  #微服务名称修改，将IP地址 换成可读性高的名字
    prefer-ip-address: true   #鼠标移至payment8001，会有ip地址提示
    #心跳监测 与 续约时间
    #开发时设置小些，保证服务关闭后 注册中心能及时的剔除服务
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2


mybatis:
  # 搜索指定包别名
  type-aliases-package: com.nr.springcloud.entities
  #typeAliasesPackage: com.nr.springcloud.entities
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml

# 日志配置
logging:
  level:
    com.nr.springcloud.*: DEBUG