server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: paymentHystrix8001  #微服务名称修改，将IP地址 换成可读性高的名字
    prefer-ip-address: true   #鼠标移至8002下 会有IP地址提示
    #心跳监测 与 续约时间
    #开发时设置小些，保证服务关闭后 注册中心能及时的剔除服务
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2

#访问豪猪图形化界面报错：If it should be allowed add it to hystrix.dashboard.proxyStreamAllowList.需添加如下配置。客户端9001也要添加
management:
  endpoints:
    web:
      exposure:
        include: "*"